# Generated by Django 4.2.9 on 2024-06-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pybo", "0006_auto_20200507_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="vote_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="vote_count",
            field=models.IntegerField(default=0),
        ),
    ]
