# Generated by Django 4.2.9 on 2024-06-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pybo", "0007_answer_vote_count_question_vote_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
